### ISSUE TITLE
Internalize utils.R functions?

### ISSUE THREAD

**Issue by pkq** [datalorax/slidex#13]
I appreciate that you documented the functions in utils.R (for people like me trying to understand the magic under the hood), but noticed they all show up in the package manual/index. Is that intentional? As you may know, individual functions can be excluded with `@keywords internal`. If you want it, I'll submit a PR for that. If not, feel free to close. 😄

**Comment by datalorax** [comment]
Yeah some of them should have the internal tag and others are missing it. I want to document all the functions but some are not documented at all yet. But they should all be internal. If you don't mind adding that tag that would be fantastic!

And thanks again for all your help. I'd be happy to add you as a contributor on the DESCRIPTION file if you'd like to add that in too.

**Comment by pkq** [comment]
Of course! Sounds good, I'll add another commit to #14 with my info.
