### ISSUE TITLE
Is there a way to force slidex to read non-us language encoding

### ISSUE THREAD

**Issue by RMHogervorst** [datalorax/slidex#4]
I could not find a way to change the language encoding of the powerpoint. 

So could I force slidex to just try it?

**Comment by datalorax** [comment]
Unfortunately all the tags in the xml tree are different so you end up with a basically blank RMD. It is certainly doable, but at this early stage I’m trying to make sure it works for English first so I can limit the number of moving parts. So thanks for your interest, and stay tuned!

**Comment by RMHogervorst** [comment]
How annoying by Microsoft! So the fields have different names in different languages? Yeah i understand that you limit the scope first. Thanks!

**Comment by datalorax** [comment]
Yeah, it is really annoying. The PPTX with non-English encoding I tested it with was really basic. If you wanted to try it out with a more complex PPT, you could fork/clone the repo, comment out lines 22-26 in export.R, then reinstall and give it a whirl. If it works at all I'd be interested to hear. (alternatively, you could just send me a PPTX and I could try it out, if you'd rather not go through the effort)

**Comment by retorquere** [comment]
This one is nl-NL

[TRAIL data-analysis and statistics Day 1.pptx](https://github.com/datalorax/slidex/files/2527208/TRAIL.data-analysis.and.statistics.Day.1.pptx)

**Comment by datalorax** [comment]
Thanks. I'll keep this one in the docket if I can ever get around to supporting other languages. I've had essentially no time to work on this as of late, unfortunately.

**Comment by lief-y** [comment]
> This one is nl-NL
> 
> [TRAIL data-analysis and statistics Day 1.pptx](https://github.com/datalorax/slidex/files/2527208/TRAIL.data-analysis.and.statistics.Day.1.pptx)

For some reasons, I noticed that the slides size has to be 16:9. And it's better to copy all slides to a new blank presentation so that the slides can be converted. However, on Windows, no image was extracted from pptx slides. If there are not many images, you may copy-paste from pptx to your Rmd file using some markdown editors that support copy-pasting images.
